---
abstract: 'Logger base class for filtering functionality'
author:
  - 'Michael Conrad <mike@nrdvana.net>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Any-Adapter-Filtered
requires:
  Carp: '0'
  Data::Dumper: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Base: '0'
  Scalar::Util: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
version: 0.000000_01
